### ISSUE TITLE
How to set `normalizeUsing` when using bamCoverage?

### ISSUE THREAD

**Issue by YiweiNiu** [harbourlab/SparK#17]
Hi,

Thanks for developing this useful tool.

I have two questions:

1. How to set `normalizeUsing` parameter when using [`bamCoverage`](https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html) from deeptools, if I want to use SparK? Also, should I use the same `normalizeUsing` method for different types of data, e.g. RNA-seq, ATAC-seq? 

2. For ATAC-seq data, should I use `bamCoverage` to generate the bedGraph files for SparK, e.g. using the parameter you mentioned `bamCoverage -b bamfile.bam -o outputfilename.bdg -bs 1 -of bedgraph`? 

Bests,
Yiwei

**Comment by harbourlab** [comment]
Hi Yiwi,

I would recommend CPM for both RNA-seq and ATAC-seq. Reason being that you are just looking at reads per million which is fine for a localized area in my option. The more fancy ways of normalizing RNA-seq (e.g. by transcripts per million is more interesting for quantitative studies, but you could to TPM for RNA-seq too if you wanted to.

Hope this helps!
Cheers
Stefan
________________________________________________________________
Stefan Kurtenbach, Ph.D.
Research Assistant Professor
Department of Ophthalmology, Bascom Palmer Eye Institute
University of Miami Miller School of Medicine
Sylvester Comprehensive Cancer Center
Director, ISCI Pluripotent Stem Cell Laboratory

Biomedical Research Building Room 913
1501 NW 10th Avenue, Miami, FL 33136
305-243-3892 office, 786-252-4379 cell
***@***.******@***.***>

On Sep 15, 2021, at 4:49 AM, Niu Yiwei ***@***.******@***.***>> wrote:

CAUTION: This email originated from outside the organization. DO NOT CLICK ON LINKS or OPEN ATTACHMENTS unless you know and trust the sender.



Hi,

Thanks for developing this useful tool.

I have two questions:

  1.  How to set normalizeUsing parameter when using bamCoverage<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeeptools.readthedocs.io%2Fen%2Fdevelop%2Fcontent%2Ftools%2FbamCoverage.html&data=04%7C01%7CStefan.Kurtenbach%40med.miami.edu%7C38dcab55dbd14d736a3c08d97825b976%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637672925707184149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4k0QKQDuw8qxZRS6XxUu%2F9RvJC8B3rTb6nO6nWjF5mI%3D&reserved=0> from deeptools, if I want to use SparK? Also, should I use the same normalizeUsing method for different types of data, e.g. RNA-seq, ATAC-seq?

  2.  For ATAC-seq data, should I use bamCoverage to generate the bedGraph files for SparK, e.g. using the parameter you mentioned bamCoverage -b bamfile.bam -o outputfilename.bdg -bs 1 -of bedgraph?

Bests,
Yiwei

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fharbourlab%2FSparK%2Fissues%2F17&data=04%7C01%7CStefan.Kurtenbach%40med.miami.edu%7C38dcab55dbd14d736a3c08d97825b976%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637672925707194140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n95u7uBWFfO4meVFYLYCXB43MxuPQtur9Ojvth6YgyU%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHANDYVN3ATXP4J7DNT2XILUCBMZNANCNFSM5EB5S2EA&data=04%7C01%7CStefan.Kurtenbach%40med.miami.edu%7C38dcab55dbd14d736a3c08d97825b976%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637672925707194140%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PYVsATi9KeJO3dkcJTSpkXJse%2FfQ3Dox5u8kZgDqIA8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CStefan.Kurtenbach%40med.miami.edu%7C38dcab55dbd14d736a3c08d97825b976%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637672925707204134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LpKRmC4yXsY%2FXWNO%2F03o17bSOraoechfNNYAvlO%2Bw%2B4%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CStefan.Kurtenbach%40med.miami.edu%7C38dcab55dbd14d736a3c08d97825b976%7C2a144b72f23942d48c0e6f0f17c48e33%7C0%7C0%7C637672925707204134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gFfkIatoDiUkeS%2Bh9QdfmsNUScsEMGCrNpEISFDWi20%3D&reserved=0>.

**Comment by YiweiNiu** [comment]
Thank you for your prompt reply. Got it now.
